@startuml

enum    SystemState{
    0 = UNCALIBRATED
    1 = CALIBRATED
    2 = STANDBY
    3 = AUTO_CYCLE
    4 = PAUSE_CYCLE
}

enum    CalibrationState{
    0 = FAST_TO_SWITCH
    1 = BACK_OFF_SWITCH
    2 = SLOW_TO_SWITCH
}

enum    CycleState{
    0 = MOVE_HOME
    1 = MOVE_TO_A
    2 = LOWER_AT_A
    3 = CLOSE_AT_A
    4 = RAISE_AT_A
    5 = MOVE_TO_B
    6 = LOWER_AT_B
    7 = OPEN_AT_B
    8 = RAISE_AT_B
    9 = MOVE_TO_C
    10 = LOWER_AT_C
    11 = CLOSE_AT_C
    12 = RAISE_AT_C
    13 = MOVE_TO_D
    14 = LOWER_AT_D
    15 = OPEN_AT_D
    16 = RETURN_HOME
}

@enduml